name: Build and Test

on:
  push:
    # branches:
    #   - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
    build:
        runs-on: ubuntu-latest
    
        steps:
        - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # 4.1.7
    
        - name: Setup Node
          uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # 4.0.3
          with:
            node-version-file: .nvmrc
            cache: 'yarn'
    
        - name: Install dependencies
          run: yarn install
    
        - name: Lint
          run: yarn lint

        - name: Build
          run: yarn build
    
        - name: Test
          run: yarn test
